run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - "github.com/stretchr/testify/require"
          - "github.com/cheggaaa/pb/v3"
          - "github.com/json-iterator/go"
          - "github.com/pelletier/go-toml"
          - "github.com/dijer/otus-go/hw12_13_14_15_calendar"
          - "github.com/jmoiron/sqlx"
          - "github.com/pressly/goose"
          - "github.com/grpc-ecosystem/grpc-gateway"
          - "github.com/lib/pq"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace