[logger]
level = "INFO"

[storage]
storage = "sql"

[database]
host = "localhost"
port = 5432
user = "otus_user"
password = "otus_password"
dbname = "exampledb"

[http]
host = "localhost"
port = 8080

[grpc]
transport = "tcp"
host = "localhost"
port = 50051
