[logger]
level = "INFO"

[storage]
storage = "sql"

[database]
host = "localhost"
port = 5432
user = "user"
password = "password"
dbname = "calendar"
migrate = "migrations"

[server]
host = "localhost"
port = 8080