# GetEventsList
GET http://localhost:8080/events/list
Content-Type: application/json

###

# AddEvent
POST http://localhost:8080/events/add
Content-Type: application/json

{
    "event": {
        "title": "test title",
        "description": "test descr",
        "start_time": "2025-01-21T12:00:00Z",
        "end_time": "2025-01-21T13:00:00Z",
        "owner": 3
    }
}

###

# UpdateEvent
PUT http://localhost:8080/events/6
Content-Type: application/json

{
    "event": {
        "title": "test title",
        "description": "test descr",
        "start_time": "2025-01-10T14:00:00Z",
        "end_time": "2025-01-10T15:00:00Z",
        "owner": 3
    }
}

###

# DeleteEvent
DELETE http://localhost:8080/events/2

###

# Hello World
GET http://localhost:8080/hello